name: dev_check
on:
  push:

jobs:
  TranslateEN:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3    
      - name: Translate
        uses: ./
        with:
          input_file: "example/test_fr.md"
          output_file: "example/test_en.md"
          output_lang: "EN-US"
          deepl_free_token: "${{ secrets.TOKEN }}"
      - name: Publish
        uses: actions/upload-artifact@v3
        with:
          name: test_en.md
          path: example/test_en.md
  TranslateZH:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3    
      - name: Translate
        uses: ./
        with:
          input_file: "example/test_fr.md"
          output_file: "example/test_zh.md"
          output_lang: "ZH"
          deepl_free_token: "${{ secrets.TOKEN }}"
      - name: Publish
        uses: actions/upload-artifact@v3
        with:
          name: test_zh.md
          path: example/test_zh.md          
