name: Reusable translate workflow

on:
  workflow_call:
    inputs:
      output_lang:
        required: true
        type: string
    secrets:
      TOKEN:
        required: true

jobs:
  translateJob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Translate
        id: translate
        uses: ./
        with:
          input_file: "docs/FR/README.md"
          output_file: "docs/${{ inputs.output_lang }}/"
          output_lang: ${{ inputs.output_lang }}
          deepl_free_token: "${{ secrets.TOKEN }}"       
      - name: Commit outputs
        continue-on-error: true
        run: |
          git config --global user.name 'deeplaction'
          git config --global user.email 'deeplaction@users.noreply.github.com'
          git pull
          echo "output="${{steps.translate.outputs.generated_file}}
          git add  ${{steps.translate.outputs.generated_file}}
          git commit -am "readme translation"
          git push
